# Generated by Django 5.0.4 on 2024-05-07 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0003_message_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='image',
            field=models.ImageField(upload_to='image'),
        ),
    ]
