# Generated by Django 5.0.4 on 2024-05-07 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0005_alter_message_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='image',
        ),
    ]
