# Generated by Django 5.0.4 on 2024-05-08 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0007_chatimage_message_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
